name = "gleam_sendgrid"
version = "0.2.0"
licences = ["Apache-2.0"]
description = "Send emails from Gleam with SendGrid"
repository = { type = "github", user = "lpil", repo = "gleam_sendgrid" }
links = [
    { title = "Website", href = "https://gleam.run" },
    { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]
gleam = ">= 1.11.0"

[dependencies]
gleam_json = ">= 3.0.2 and < 4.0.0"
gleam_http = ">= 4.1.0 and < 5.0.0"

[dev-dependencies]
gleeunit = ">= 1.6.0 and < 2.0.0"
gleam_hackney = ">= 1.3.1 and < 2.0.0"
