name = "gleam_sendgrid"
version = "0.1.1"
licences = ["Apache-2.0"]
description = "Send emails from Gleam with SendGrid"
repository = { type = "github", user = "lpil", repo = "gleam_sendgrid" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.19"
gleam_http = "~> 3.0"
gleam_json = "~> 0.4"

[dev-dependencies]
gleeunit = "~> 0.6"
gleam_hackney = "~> 0.2"
